name: lint

on: [push, pull_request, workflow_dispatch]

permissions:
    contents: write

jobs:
    semgrep:
        runs-on: ubuntu-latest
        container:
            image: returntocorp/semgrep:1.1.0
        if: (github.actor != 'dependabot[bot]')
        steps:
            - uses: actions/checkout@v3

            - name: "Execute Semgrep"
              run: semgrep ci
              env:
                    SEMGREP_RULES: p/default