name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v4
        with:
            go-version: ${{matrix.go-version}}
    
      - name: Run Tests
        run: go test ./...


